export const LOAD_APPLICATION_LIST = 'LOAD_APPLICATION_LIST'
export const ADD_APPLICATION = 'ADD_APPLICATION'
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION'
export const DELETE_APPLICATION = 'DELETE_APPLICATION'
